apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: nginx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
