apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    metadata:
      labels:
        environment: staging
    spec:
      containers:
      - name: my-app
        image: nginx:1.21
